#!/usr/bin/env python3
"""
build_seeds.py  —  generate the PostgreSQL seed SQL for the bonus lootboxes.

Single source of truth = the pet JSON files in tools/sprite_forge/pets/. This
script reads the 4 bonus-box files, pulls each behaviour's frames/fps straight
from ascii_to_sprites.BEHAVIOR_ANIM (so the `animations` JSON can never drift
from the sprites the forge actually rendered), and writes two SQL files:

    fastapi-server/seeds/custom/seed_custom_pet_species.sql   (40 pets, by box)
    fastapi-server/seeds/custom/seed_custom_lootboxes.sql     (4 lootboxes)

Pets and lootboxes are kept in SEPARATE files, and within each file every box is
its own clearly-bannered BEGIN/COMMIT section — nothing is interleaved.

Price + per-rarity odds are copied from the existing `ai_slop` box (price 50000;
common 78 / uncommon 14 / rare 5 / epic 2 / legendary 1).

    python tools/sprite_forge/build_seeds.py
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, HERE)
import ascii_to_sprites as forge  # noqa: E402  (BEHAVIOR_ANIM lives here)

# ---- shared knobs, lifted from the ai_slop lootbox --------------------------
PRICE = 50000
RARITY_ODDS = {"common": 78, "uncommon": 14, "rare": 5, "epic": 2, "legendary": 1}
RARITY_ORDER = ["common", "uncommon", "rare", "epic", "legendary"]

# ---- the 4 bonus boxes: (pets file, lootbox sku, display name) ---------------
BOXES = [
    ("breakfast_brigade.json", "breakfast_brigade", "Breakfast Brigade"),
    ("cryptid_corner.json",    "cryptid_corner",    "Cryptid Corner"),
    ("haunted_hardware.json",  "haunted_hardware",  "Haunted Hardware"),
    ("barnyard_blunders.json", "barnyard_blunders", "Barnyard Blunders"),
]

OUT_DIR = os.path.join(REPO, "fastapi-server", "seeds", "custom")


def sql_str(s):
    """A single-quoted SQL string literal (doubles embedded quotes)."""
    return "'" + str(s).replace("'", "''") + "'"


def compact_json(obj):
    return json.dumps(obj, separators=(",", ":"))


def load_box(path):
    """Ordered list of (species_id, spec) for one box file, skipping _meta keys."""
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    pets = []
    for sid, spec in data.items():
        if sid.startswith("_"):
            continue
        pets.append((sid, spec))
    return pets


def behaviors_of(spec):
    """Unique, order-preserving behaviour list (the bag may contain duplicates)."""
    bag = spec.get("bag") or spec.get("behaviors") or []
    return list(dict.fromkeys(bag))


def species_config(spec):
    """The pet_species.config JSON: behaviorBag + per-behaviour animations."""
    bag = spec.get("bag") or spec.get("behaviors") or []
    anims = {}
    for b in behaviors_of(spec):
        frames, fps, _style = forge.BEHAVIOR_ANIM[b]
        anims[b] = {"frameWidth": 64, "frameHeight": 64, "frames": frames, "fps": fps}
    return {"behaviorBag": bag, "animations": anims}


def species_values_row(sid, spec):
    cfg = compact_json(species_config(spec))
    return (
        f"    ({sql_str(sid)}, {sql_str(spec['display_name'])}, "
        f"{sql_str(spec['rarity'])}, 64, 64, {int(spec['speed'])}, "
        f"{sql_str(cfg)}::json, true)"
    )


def drop_table_for(pets):
    by_rarity = {}
    for sid, spec in pets:
        by_rarity.setdefault(spec["rarity"], []).append(sid)
    # invariant the roller relies on: every odds key must have >=1 species
    missing = [r for r in RARITY_ODDS if not by_rarity.get(r)]
    if missing:
        raise SystemExit(f"box is missing species for rarities {missing}")
    species_by_rarity = {r: by_rarity[r] for r in RARITY_ORDER if r in by_rarity}
    return {"rarities": RARITY_ODDS, "speciesByRarity": species_by_rarity}


SPECIES_HEADER = """\
-- ============================================================================
--  seed_custom_pet_species.sql  —  bonus-lootbox pet catalog (PostgreSQL)
-- ============================================================================
--  GENERATED by tools/sprite_forge/build_seeds.py — do not hand-edit; edit the
--  pet JSON in tools/sprite_forge/pets/ and re-run the generator instead.
--
--  Target DB : the FastAPI Postgres database (DATABASE_URL).
--  Prereq    : `alembic upgrade head`, and the sprite PNGs must exist
--              (python tools/sprite_forge/ascii_to_sprites.py).
--  Run       : psql "$DATABASE_URL" -f fastapi-server/seeds/custom/seed_custom_pet_species.sql
--  Idempotent: ON CONFLICT (species_id) DO NOTHING -> safe to re-run.
--  Leaves the original seed_pet_species.sql / seed_lootboxes.sql untouched.
--  Each box is its own BEGIN/COMMIT section below; pets are never interleaved
--  between boxes, and the lootbox rows live in seed_custom_lootboxes.sql.
-- ============================================================================
"""

LOOTBOX_HEADER = """\
-- ============================================================================
--  seed_custom_lootboxes.sql  —  4 bonus lootbox SKUs + drop tables (PostgreSQL)
-- ============================================================================
--  GENERATED by tools/sprite_forge/build_seeds.py — do not hand-edit.
--
--  Price + per-rarity odds are copied from the existing `ai_slop` box
--  (price 50000; common 78 / uncommon 14 / rare 5 / epic 2 / legendary 1).
--  drop_table is server-only (never sent to the client); only per-rarity odds
--  are exposed. Invariant: every key in "rarities" also appears in
--  "speciesByRarity" (else the roll KeyErrors) — enforced by the generator.
--
--  Run : psql "$DATABASE_URL" -f fastapi-server/seeds/custom/seed_custom_lootboxes.sql
--  Idempotent: ON CONFLICT (sku) DO NOTHING. Pairs with seed_custom_pet_species.sql.
--  Each lootbox is its own BEGIN/COMMIT section; nothing is interleaved.
-- ============================================================================
"""


def banner(title):
    return ("-- " + "-" * 73 + "\n"
            f"--  {title}\n"
            "-- " + "-" * 73 + "\n")


def build():
    species_parts = [SPECIES_HEADER]
    lootbox_parts = [LOOTBOX_HEADER]
    all_skus = []
    all_species_ids = []

    for fname, sku, name in BOXES:
        pets = load_box(os.path.join(HERE, "pets", fname))
        all_skus.append(sku)
        all_species_ids += [sid for sid, _ in pets]

        # ---- pet species section for this box ----
        rows = ",\n".join(species_values_row(sid, spec) for sid, spec in pets)
        species_parts.append(
            "\n" + banner(f"{name}  ({len(pets)} pets)")
            + "BEGIN;\n\n"
            + "INSERT INTO pet_species\n"
            + "    (species_id, display_name, rarity, width, height, default_speed_x100, config, enabled)\n"
            + "VALUES\n"
            + rows + "\n"
            + "ON CONFLICT (species_id) DO NOTHING;\n\n"
            + "COMMIT;\n"
        )

        # ---- lootbox section for this box ----
        drop = compact_json(drop_table_for(pets))
        lootbox_parts.append(
            "\n" + banner(f"{name}")
            + "BEGIN;\n\n"
            + "INSERT INTO lootboxes (sku, name, price, drop_table, enabled)\n"
            + "VALUES\n"
            + f"    ({sql_str(sku)}, {sql_str(name)}, {PRICE}, {sql_str(drop)}::json, true)\n"
            + "ON CONFLICT (sku) DO NOTHING;\n\n"
            + "COMMIT;\n"
        )

    # ---- rollback footers ----
    species_parts.append(
        "\n-- ----------------------------------------------------------------------------\n"
        "-- Rollback (uncomment to remove exactly these species):\n"
        "-- BEGIN;\n-- DELETE FROM pet_species WHERE species_id IN (\n"
        + "--   " + ", ".join(sql_str(s) for s in all_species_ids) + "\n"
        "-- );\n-- COMMIT;\n"
        "-- NOTE: fails if a pet_instances row references one (FK). Delete those first.\n"
    )
    lootbox_parts.append(
        "\n-- ----------------------------------------------------------------------------\n"
        "-- Rollback (uncomment to remove exactly these lootboxes):\n"
        "-- BEGIN;\n-- DELETE FROM lootboxes WHERE sku IN (\n"
        + "--   " + ", ".join(sql_str(s) for s in all_skus) + "\n"
        "-- );\n-- COMMIT;\n"
    )

    os.makedirs(OUT_DIR, exist_ok=True)
    sp = os.path.join(OUT_DIR, "seed_custom_pet_species.sql")
    lb = os.path.join(OUT_DIR, "seed_custom_lootboxes.sql")
    with open(sp, "w", encoding="utf-8", newline="\n") as f:
        f.write("".join(species_parts))
    with open(lb, "w", encoding="utf-8", newline="\n") as f:
        f.write("".join(lootbox_parts))

    print(f"wrote {sp}\n      ({len(all_species_ids)} species across {len(BOXES)} boxes)")
    print(f"wrote {lb}\n      ({len(all_skus)} lootboxes)")


if __name__ == "__main__":
    build()
