"""remove foreign key contraint on lootbox open

Revision ID: 20d3ff60db7b
Revises: 21b699f83ffa
Create Date: 2026-07-08 20:49:29.406597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d3ff60db7b'
down_revision: Union[str, Sequence[str], None] = '21b699f83ffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('lootbox_opens_pet_instance_id_fkey'), 'lootbox_opens', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('lootbox_opens_pet_instance_id_fkey'), 'lootbox_opens', 'pet_instances', ['pet_instance_id'], ['id'])
    # ### end Alembic commands ###
