"""battle tables

Revision ID: 21b699f83ffa
Revises: c0ccf708df74
Create Date: 2026-07-08 09:57:29.354801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21b699f83ffa'
down_revision: Union[str, Sequence[str], None] = 'c0ccf708df74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battle_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('trophies', sa.Integer(), server_default='0', nullable=False),
    sa.Column('wins', sa.Integer(), server_default='0', nullable=False),
    sa.Column('losses', sa.Integer(), server_default='0', nullable=False),
    sa.Column('streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('best_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name')
    )
    op.create_index(op.f('ix_battle_teams_user_id'), 'battle_teams', ['user_id'], unique=False)
    op.create_table('battle_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=8), nullable=False),
    sa.Column('reward', sa.Integer(), nullable=False),
    sa.Column('trophies_after', sa.Integer(), nullable=False),
    sa.Column('enemy_tier', sa.Integer(), nullable=False),
    sa.Column('seed_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['battle_teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battle_logs_team_id'), 'battle_logs', ['team_id'], unique=False)
    op.create_index(op.f('ix_battle_logs_user_id'), 'battle_logs', ['user_id'], unique=False)
    op.create_table('battle_team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('pet_instance_id', sa.String(length=36), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pet_instance_id'], ['pet_instances.instance_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['battle_teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'pet_instance_id'),
    sa.UniqueConstraint('team_id', 'slot')
    )
    op.add_column('pet_instances', sa.Column('level', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet_instances', 'level')
    op.drop_table('battle_team_members')
    op.drop_index(op.f('ix_battle_logs_user_id'), table_name='battle_logs')
    op.drop_index(op.f('ix_battle_logs_team_id'), table_name='battle_logs')
    op.drop_table('battle_logs')
    op.drop_index(op.f('ix_battle_teams_user_id'), table_name='battle_teams')
    op.drop_table('battle_teams')
    # ### end Alembic commands ###
