"""user themes

Revision ID: 29d381dabaa1
Revises: b02778452fcd
Create Date: 2026-05-03 23:15:49.833358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29d381dabaa1'
down_revision: Union[str, Sequence[str], None] = 'b02778452fcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'theme', name='uq_user_theme')
    )
    op.create_index(op.f('ix_user_themes_user_id'), 'user_themes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_themes_user_id'), table_name='user_themes')
    op.drop_table('user_themes')
    # ### end Alembic commands ###
