"""pet and lootbox tables

Revision ID: c0ccf708df74
Revises: e841a2c01f13
Create Date: 2026-05-28 21:12:05.669145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0ccf708df74'
down_revision: Union[str, Sequence[str], None] = 'e841a2c01f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lootboxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('drop_table', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('pet_species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('rarity', sa.String(length=16), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('default_speed_x100', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pet_species_rarity'), 'pet_species', ['rarity'], unique=False)
    op.create_index(op.f('ix_pet_species_species_id'), 'pet_species', ['species_id'], unique=True)
    op.create_table('pet_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.String(length=64), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['pet_species.species_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id')
    )
    op.create_index(op.f('ix_pet_instances_species_id'), 'pet_instances', ['species_id'], unique=False)
    op.create_index(op.f('ix_pet_instances_user_id'), 'pet_instances', ['user_id'], unique=False)
    op.create_table('lootbox_opens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=32), nullable=False),
    sa.Column('rolled_rarity', sa.String(length=16), nullable=False),
    sa.Column('rolled_species', sa.String(length=64), nullable=False),
    sa.Column('pet_instance_id', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pet_instance_id'], ['pet_instances.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lootbox_opens_user_id'), 'lootbox_opens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lootbox_opens_user_id'), table_name='lootbox_opens')
    op.drop_table('lootbox_opens')
    op.drop_index(op.f('ix_pet_instances_user_id'), table_name='pet_instances')
    op.drop_index(op.f('ix_pet_instances_species_id'), table_name='pet_instances')
    op.drop_table('pet_instances')
    op.drop_index(op.f('ix_pet_species_species_id'), table_name='pet_species')
    op.drop_index(op.f('ix_pet_species_rarity'), table_name='pet_species')
    op.drop_table('pet_species')
    op.drop_table('lootboxes')
    # ### end Alembic commands ###
