"""blackjack table

Revision ID: c2b46f832a7f
Revises: ab3b7ec53f39
Create Date: 2026-05-02 23:32:20.787575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2b46f832a7f'
down_revision: Union[str, Sequence[str], None] = 'ab3b7ec53f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blackjack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('player_hands', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dealer_hand', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deck_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bet_amount', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blackjack_user_id'), 'blackjack', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blackjack_user_id'), table_name='blackjack')
    op.drop_table('blackjack')
    # ### end Alembic commands ###
