"""change user id to name on messages

Revision ID: e841a2c01f13
Revises: ffd431139a71
Create Date: 2026-05-05 22:49:07.527717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e841a2c01f13'
down_revision: Union[str, Sequence[str], None] = 'ffd431139a71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender_name', sa.String(), nullable=False))
    op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
    op.drop_column('messages', 'sender_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.drop_column('messages', 'sender_name')
    # ### end Alembic commands ###
