"""pet battles

Revision ID: ead7219b9bc3
Revises: c0ccf708df74
Create Date: 2026-06-27 17:44:49.801165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ead7219b9bc3'
down_revision: Union[str, Sequence[str], None] = 'c0ccf708df74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battle_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=8), nullable=False),
    sa.Column('reward', sa.Integer(), nullable=False),
    sa.Column('trophies_after', sa.Integer(), nullable=False),
    sa.Column('enemy_tier', sa.Integer(), nullable=False),
    sa.Column('seed_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battle_logs_user_id'), 'battle_logs', ['user_id'], unique=False)
    op.create_table('battle_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trophies', sa.Integer(), server_default='0', nullable=False),
    sa.Column('wins', sa.Integer(), server_default='0', nullable=False),
    sa.Column('losses', sa.Integer(), server_default='0', nullable=False),
    sa.Column('streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('best_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('team', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battle_profiles_user_id'), 'battle_profiles', ['user_id'], unique=True)
    op.add_column('pet_instances', sa.Column('level', sa.Integer(), server_default='1', nullable=False))
    op.add_column('pet_instances', sa.Column('xp', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet_instances', 'xp')
    op.drop_column('pet_instances', 'level')
    op.drop_index(op.f('ix_battle_profiles_user_id'), table_name='battle_profiles')
    op.drop_table('battle_profiles')
    op.drop_index(op.f('ix_battle_logs_user_id'), table_name='battle_logs')
    op.drop_table('battle_logs')
    # ### end Alembic commands ###
