"""add category to leaderboard

Revision ID: f99c7fbfd7ef
Revises: 28911b064d94
Create Date: 2026-04-26 21:49:58.155852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f99c7fbfd7ef'
down_revision: Union[str, Sequence[str], None] = '28911b064d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaderboard', sa.Column('category', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leaderboard', 'category')
    # ### end Alembic commands ###
