-- ============================================================================
--  seed_custom_lootboxes.sql  —  4 bonus lootbox SKUs + drop tables (PostgreSQL)
-- ============================================================================
--  GENERATED by tools/sprite_forge/build_seeds.py — do not hand-edit.
--
--  Price + per-rarity odds are copied from the existing `ai_slop` box
--  (price 50000; common 78 / uncommon 14 / rare 5 / epic 2 / legendary 1).
--  drop_table is server-only (never sent to the client); only per-rarity odds
--  are exposed. Invariant: every key in "rarities" also appears in
--  "speciesByRarity" (else the roll KeyErrors) — enforced by the generator.
--
--  Run : psql "$DATABASE_URL" -f fastapi-server/seeds/custom/seed_custom_lootboxes.sql
--  Idempotent: ON CONFLICT (sku) DO NOTHING. Pairs with seed_custom_pet_species.sql.
--  Each lootbox is its own BEGIN/COMMIT section; nothing is interleaved.
-- ============================================================================

-- -------------------------------------------------------------------------
--  Breakfast Brigade
-- -------------------------------------------------------------------------
BEGIN;

INSERT INTO lootboxes (sku, name, price, drop_table, enabled)
VALUES
    ('breakfast_brigade', 'Breakfast Brigade', 50000, '{"rarities":{"common":78,"uncommon":14,"rare":5,"epic":2,"legendary":1},"speciesByRarity":{"common":["angry_toast","soggy_cereal","lil_pancake","bean_buddy"],"uncommon":["sir_bacon","eggward"],"rare":["waffle_lord","milk_gone_bad"],"epic":["captain_avocado"],"legendary":["the_big_breakfast"]}}'::json, true)
ON CONFLICT (sku) DO NOTHING;

COMMIT;

-- -------------------------------------------------------------------------
--  Cryptid Corner
-- -------------------------------------------------------------------------
BEGIN;

INSERT INTO lootboxes (sku, name, price, drop_table, enabled)
VALUES
    ('cryptid_corner', 'Cryptid Corner', 50000, '{"rarities":{"common":78,"uncommon":14,"rare":5,"epic":2,"legendary":1},"speciesByRarity":{"common":["smol_foot","derp_nessie","mothboi","goblino"],"uncommon":["jackalope","chupa_pup"],"rare":["yeti_cube","mini_mothman"],"epic":["lake_lizard"],"legendary":["the_ogopogo"]}}'::json, true)
ON CONFLICT (sku) DO NOTHING;

COMMIT;

-- -------------------------------------------------------------------------
--  Haunted Hardware
-- -------------------------------------------------------------------------
BEGIN;

INSERT INTO lootboxes (sku, name, price, drop_table, enabled)
VALUES
    ('haunted_hardware', 'Haunted Hardware', 50000, '{"rarities":{"common":78,"uncommon":14,"rare":5,"epic":2,"legendary":1},"speciesByRarity":{"common":["floppy_disk","usb_stick","dead_battery","angry_router"],"uncommon":["roomba_lost","crt_goblin"],"rare":["bsod_ghost","toasted_toaster"],"epic":["printer_jam"],"legendary":["the_mainframe"]}}'::json, true)
ON CONFLICT (sku) DO NOTHING;

COMMIT;

-- -------------------------------------------------------------------------
--  Barnyard Blunders
-- -------------------------------------------------------------------------
BEGIN;

INSERT INTO lootboxes (sku, name, price, drop_table, enabled)
VALUES
    ('barnyard_blunders', 'Barnyard Blunders', 50000, '{"rarities":{"common":78,"uncommon":14,"rare":5,"epic":2,"legendary":1},"speciesByRarity":{"common":["confused_goose","round_pigeon","screaming_goat","derpy_duckling"],"uncommon":["chonk_capybara","shrimp_fella"],"rare":["axolotl_pal","llama_drama"],"epic":["cow_unbalanced"],"legendary":["the_goose_prime"]}}'::json, true)
ON CONFLICT (sku) DO NOTHING;

COMMIT;

-- ----------------------------------------------------------------------------
-- Rollback (uncomment to remove exactly these lootboxes):
-- BEGIN;
-- DELETE FROM lootboxes WHERE sku IN (
--   'breakfast_brigade', 'cryptid_corner', 'haunted_hardware', 'barnyard_blunders'
-- );
-- COMMIT;
