-- ============================================================================
--  seed_custom_pet_species.sql  —  bonus-lootbox pet catalog (PostgreSQL)
-- ============================================================================
--  GENERATED by tools/sprite_forge/build_seeds.py — do not hand-edit; edit the
--  pet JSON in tools/sprite_forge/pets/ and re-run the generator instead.
--
--  Target DB : the FastAPI Postgres database (DATABASE_URL).
--  Prereq    : `alembic upgrade head`, and the sprite PNGs must exist
--              (python tools/sprite_forge/ascii_to_sprites.py).
--  Run       : psql "$DATABASE_URL" -f fastapi-server/seeds/custom/seed_custom_pet_species.sql
--  Idempotent: ON CONFLICT (species_id) DO NOTHING -> safe to re-run.
--  Leaves the original seed_pet_species.sql / seed_lootboxes.sql untouched.
--  Each box is its own BEGIN/COMMIT section below; pets are never interleaved
--  between boxes, and the lootbox rows live in seed_custom_lootboxes.sql.
-- ============================================================================

-- -------------------------------------------------------------------------
--  Breakfast Brigade  (10 pets)
-- -------------------------------------------------------------------------
BEGIN;

INSERT INTO pet_species
    (species_id, display_name, rarity, width, height, default_speed_x100, config, enabled)
VALUES
    ('angry_toast', 'Angry Toast', 'common', 64, 64, 250, '{"behaviorBag":["idle","wander","wander","jitter"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"jitter":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":16}}}'::json, true),
    ('soggy_cereal', 'Soggy Cereal', 'common', 64, 64, 80, '{"behaviorBag":["idle","idle","sleep","wander"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"sleep":{"frameWidth":64,"frameHeight":64,"frames":4,"fps":2},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7}}}'::json, true),
    ('lil_pancake', 'Lil'' Pancake Stack', 'common', 64, 64, 200, '{"behaviorBag":["idle","wander","hop","hop"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"hop":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":9}}}'::json, true),
    ('bean_buddy', 'Coffee Bean Buddy', 'common', 64, 64, 600, '{"behaviorBag":["idle","wander","vibrate","vibrate"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"vibrate":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":18}}}'::json, true),
    ('sir_bacon', 'Sir Bacon', 'uncommon', 64, 64, 200, '{"behaviorBag":["idle","wander","headbang"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"headbang":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":12}}}'::json, true),
    ('eggward', 'Eggward', 'uncommon', 64, 64, 150, '{"behaviorBag":["idle","wander","jitter","sleep"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"jitter":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":16},"sleep":{"frameWidth":64,"frameHeight":64,"frames":4,"fps":2}}}'::json, true),
    ('waffle_lord', 'The Waffle Lord', 'rare', 64, 64, 200, '{"behaviorBag":["idle","wander","dance","dance"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"dance":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":10}}}'::json, true),
    ('milk_gone_bad', 'Milk (Expired)', 'rare', 64, 64, 300, '{"behaviorBag":["idle","wander","panic"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"panic":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":16}}}'::json, true),
    ('captain_avocado', 'Captain Avocado', 'epic', 64, 64, 400, '{"behaviorBag":["idle","wander","backflip","backflip"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"backflip":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":12}}}'::json, true),
    ('the_big_breakfast', 'THE Big Breakfast', 'legendary', 64, 64, 300, '{"behaviorBag":["idle","wander","dance","hop"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"dance":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":10},"hop":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":9}}}'::json, true)
ON CONFLICT (species_id) DO NOTHING;

COMMIT;

-- -------------------------------------------------------------------------
--  Cryptid Corner  (10 pets)
-- -------------------------------------------------------------------------
BEGIN;

INSERT INTO pet_species
    (species_id, display_name, rarity, width, height, default_speed_x100, config, enabled)
VALUES
    ('smol_foot', 'Smol Foot', 'common', 64, 64, 200, '{"behaviorBag":["idle","wander","hop"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"hop":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":9}}}'::json, true),
    ('derp_nessie', 'Derp Nessie', 'common', 64, 64, 150, '{"behaviorBag":["idle","wander","float","float"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"float":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":6}}}'::json, true),
    ('mothboi', 'Moth Boi', 'common', 64, 64, 300, '{"behaviorBag":["idle","wander","orbit","orbit"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"orbit":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":9}}}'::json, true),
    ('goblino', 'Lil'' Goblino', 'common', 64, 64, 350, '{"behaviorBag":["idle","wander","panic","panic"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"panic":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":16}}}'::json, true),
    ('jackalope', 'Jackalope', 'uncommon', 64, 64, 800, '{"behaviorBag":["idle","wander","zoomies","zoomies"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"zoomies":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":14}}}'::json, true),
    ('chupa_pup', 'Chupacabra Pup', 'uncommon', 64, 64, 500, '{"behaviorBag":["idle","wander","flee_cursor"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"flee_cursor":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":12}}}'::json, true),
    ('yeti_cube', 'Yeti Cube', 'rare', 64, 64, 250, '{"behaviorBag":["idle","wander","roll","roll"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"roll":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":12}}}'::json, true),
    ('mini_mothman', 'Mothman (Travel Size)', 'rare', 64, 64, 300, '{"behaviorBag":["idle","float","follow_cursor"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"float":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":6},"follow_cursor":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":9}}}'::json, true),
    ('lake_lizard', 'Lake Lizard', 'epic', 64, 64, 350, '{"behaviorBag":["idle","wander","headbang"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"headbang":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":12}}}'::json, true),
    ('the_ogopogo', 'Ogopogo Prime', 'legendary', 64, 64, 300, '{"behaviorBag":["idle","wander","float","dance"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"float":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":6},"dance":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":10}}}'::json, true)
ON CONFLICT (species_id) DO NOTHING;

COMMIT;

-- -------------------------------------------------------------------------
--  Haunted Hardware  (10 pets)
-- -------------------------------------------------------------------------
BEGIN;

INSERT INTO pet_species
    (species_id, display_name, rarity, width, height, default_speed_x100, config, enabled)
VALUES
    ('floppy_disk', 'Haunted Floppy', 'common', 64, 64, 200, '{"behaviorBag":["idle","wander","jitter"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"jitter":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":16}}}'::json, true),
    ('usb_stick', 'USB (Wrong Way)', 'common', 64, 64, 250, '{"behaviorBag":["idle","wander","backflip","backflip"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"backflip":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":12}}}'::json, true),
    ('dead_battery', 'Dead Battery', 'common', 64, 64, 30, '{"behaviorBag":["idle","idle","sleep","sleep","wander"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"sleep":{"frameWidth":64,"frameHeight":64,"frames":4,"fps":2},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7}}}'::json, true),
    ('angry_router', 'Rage Router', 'common', 64, 64, 200, '{"behaviorBag":["idle","wander","vibrate","vibrate"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"vibrate":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":18}}}'::json, true),
    ('roomba_lost', 'Lost Roomba', 'uncommon', 64, 64, 400, '{"behaviorBag":["idle","wander","zoomies","zoomies"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"zoomies":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":14}}}'::json, true),
    ('crt_goblin', 'CRT Gremlin', 'uncommon', 64, 64, 250, '{"behaviorBag":["idle","wander","jitter","teleport"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"jitter":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":16},"teleport":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":10}}}'::json, true),
    ('bsod_ghost', 'BSOD Phantom', 'rare', 64, 64, 300, '{"behaviorBag":["idle","float","teleport","teleport"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"float":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":6},"teleport":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":10}}}'::json, true),
    ('toasted_toaster', 'Cursed Toaster', 'rare', 64, 64, 250, '{"behaviorBag":["idle","wander","hop","hop"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"hop":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":9}}}'::json, true),
    ('printer_jam', 'Printer of Doom', 'epic', 64, 64, 300, '{"behaviorBag":["idle","wander","panic","recoil"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"panic":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":16},"recoil":{"frameWidth":64,"frameHeight":64,"frames":4,"fps":12}}}'::json, true),
    ('the_mainframe', 'THE Mainframe', 'legendary', 64, 64, 200, '{"behaviorBag":["idle","wander","spin","dance"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"spin":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":12},"dance":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":10}}}'::json, true)
ON CONFLICT (species_id) DO NOTHING;

COMMIT;

-- -------------------------------------------------------------------------
--  Barnyard Blunders  (10 pets)
-- -------------------------------------------------------------------------
BEGIN;

INSERT INTO pet_species
    (species_id, display_name, rarity, width, height, default_speed_x100, config, enabled)
VALUES
    ('confused_goose', 'Confused Goose', 'common', 64, 64, 400, '{"behaviorBag":["idle","wander","panic","panic"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"panic":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":16}}}'::json, true),
    ('round_pigeon', 'Spherical Pigeon', 'common', 64, 64, 250, '{"behaviorBag":["idle","wander","hop","hop"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"hop":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":9}}}'::json, true),
    ('screaming_goat', 'Screaming Goat', 'common', 64, 64, 200, '{"behaviorBag":["idle","wander","headbang","headbang"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"headbang":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":12}}}'::json, true),
    ('derpy_duckling', 'Derpy Duckling', 'common', 64, 64, 300, '{"behaviorBag":["idle","wander","follow_cursor"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"follow_cursor":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":9}}}'::json, true),
    ('chonk_capybara', 'Chonk Capybara', 'uncommon', 64, 64, 60, '{"behaviorBag":["idle","idle","sleep","sleep","wander"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"sleep":{"frameWidth":64,"frameHeight":64,"frames":4,"fps":2},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7}}}'::json, true),
    ('shrimp_fella', 'Shrimp Fella', 'uncommon', 64, 64, 300, '{"behaviorBag":["idle","wander","jitter","jitter"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"jitter":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":16}}}'::json, true),
    ('axolotl_pal', 'Axolotl Pal', 'rare', 64, 64, 200, '{"behaviorBag":["idle","wander","float","float"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"float":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":6}}}'::json, true),
    ('llama_drama', 'Drama Llama', 'rare', 64, 64, 250, '{"behaviorBag":["idle","wander","dance","dance"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"dance":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":10}}}'::json, true),
    ('cow_unbalanced', 'Unstable Cow', 'epic', 64, 64, 300, '{"behaviorBag":["idle","wander","roll","hop"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"roll":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":12},"hop":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":9}}}'::json, true),
    ('the_goose_prime', 'GOOSE PRIME', 'legendary', 64, 64, 600, '{"behaviorBag":["idle","wander","zoomies","panic"],"animations":{"idle":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":4},"wander":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":7},"zoomies":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":14},"panic":{"frameWidth":64,"frameHeight":64,"frames":6,"fps":16}}}'::json, true)
ON CONFLICT (species_id) DO NOTHING;

COMMIT;

-- ----------------------------------------------------------------------------
-- Rollback (uncomment to remove exactly these species):
-- BEGIN;
-- DELETE FROM pet_species WHERE species_id IN (
--   'angry_toast', 'soggy_cereal', 'lil_pancake', 'bean_buddy', 'sir_bacon', 'eggward', 'waffle_lord', 'milk_gone_bad', 'captain_avocado', 'the_big_breakfast', 'smol_foot', 'derp_nessie', 'mothboi', 'goblino', 'jackalope', 'chupa_pup', 'yeti_cube', 'mini_mothman', 'lake_lizard', 'the_ogopogo', 'floppy_disk', 'usb_stick', 'dead_battery', 'angry_router', 'roomba_lost', 'crt_goblin', 'bsod_ghost', 'toasted_toaster', 'printer_jam', 'the_mainframe', 'confused_goose', 'round_pigeon', 'screaming_goat', 'derpy_duckling', 'chonk_capybara', 'shrimp_fella', 'axolotl_pal', 'llama_drama', 'cow_unbalanced', 'the_goose_prime'
-- );
-- COMMIT;
-- NOTE: fails if a pet_instances row references one (FK). Delete those first.
